### ISSUE TITLE
Moon Art (Player)

### ISSUE THREAD

**Issue by embydesign** [fps-game-jam-org/game-off-2020#13]
- General Look
- Phases of Destruction
- Debris

**Comment by MJ3dart** [comment]
![Moon](https://user-images.githubusercontent.com/71523858/99925317-b46f1100-2d0b-11eb-906e-a900e83a806e.png)

**Comment by MJ3dart** [comment]
![MoonAnimation](https://user-images.githubusercontent.com/71523858/99981198-16189500-2d77-11eb-9d73-565be5d8933a.png)
